### PR TITLE
german translations part2

### PR DESCRIPTION
**Pull request by Constey**
Hi @nbelyh,

i've added the missing strings within the manifest and the other files. should be all now :-)
(Did not translate the console.log messages...)
I'm somehow to stupid to auto merge our commits, so i've added your updated package.json within my commit.

Kind regards,
Constantin

### CODE REVIEW

**Comment by nbelyh** [comment]
Thank you so much. I've just included one a [dependabot] pull request. Will resolve the conflict and merge.

**Comment by nbelyh** [comment]
Fixed the build also, so that it does not try to deploy every PR to Github releases, but just builds 😅

**Comment by nbelyh** [comment]
@Constey I've erroneously committed the PR from [Dependabot], that updated one of SPFx modules to broken 1.16.0 while the rest now are 1.15.2, reverted. All must be updated at once (later). Also one string was missing in en-us version (label for the "Configure" button), maybe merged incorrectly. Now should be okay. Please take the latest after merge, should be fine.

**Comment by Constey** [comment]
> @Constey I've erroneously committed the PR from [Dependabot], that updated one of SPFx modules to broken 1.16.0 while the rest now are 1.15.2, reverted. All must be updated at once (later). Also one string was missing in en-us version (label for the "Configure" button), maybe merged incorrectly. Now should be okay. Please take the latest after merge, should be fine.

maybe i've missed it - but i've tested the version - seems good so far :-)

**Comment by nbelyh** [comment]
@Constey The size of the package increased to 2MB instead of 300KB (i.e. 7x times) with that accepted Dependabot PR (now reverted back, so it should be fine). This is a problem with SPFx 1.16.0 (they forgot to turn on the minification there). It was fixed in 1.16.1, but all SPFx modules need to be updated at once.

**Pull request merged**
